[package]
name = "hecs-schedule"
version = "0.1.0"
edition = "2021"
description = "Provides shedulable systems and paralell execution for hecs"
readme ="README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.7"
smallvec = "1.7.0"
